export const importantPoints = [
  {
    id: 1,
    name: "Finca La Gloria",
    image: "/maps/finca_la_gloria.webp",
    position: { lat: 20.869128, lng: -76.653746 },
    icon: "1",
    simbology: [
      "-Viviendas Familaries",
      "-Mini-Industria La Gloria",
      "-Corrales para cerdos",
      "-Vaguada",
    ],
  },
  {
    id: 2,
    name: "Finca El Troncón y El Carmen",
    image: "/maps/finca_el_troncon.webp",
    position: { lat: 20.86979227902078, lng: -76.65062229885747 },
    icon: "2",
    simbology: [
      "-Viviendas Familaries",
      "-Área de 18 especies exóticas",
      "-Vaguada",
    ],
  },
  {
    id: 3,
    name: "Finca La Bendecida",
    image: "/maps/finca_la_bendecida.webp",
    position: { lat: 20.88586, lng: -76.66603 },
    icon: "3",
    simbology: [
      "1-Viviendas Familaries",
      "2-Área de Mini-Industria ",
      "3-Pressa El Zorral",
    ],
  },
  {
    id: 4,
    name: "Finca Las Maravillas",
    image: "/maps/finca_las_maravillas.webp",
    position: { lat: 20.86202, lng: -76.62822 },
    icon: "4",
    simbology: [
      "1-Viviendas Familaries",
      "2-Área de cultivo de caña ",
      "3-Área de cultivos varios",
    ],
  },
  {
    id: 5,
    name: "Finca La Próspera",
    image: "/maps/finca_la_prospera.webp",
    position: { lat: 20.90925, lng: -76.6241 },
    icon: "5",
    simbology: [
      "1-Viviendas Familaries",
      "2-Área de cultivos varios",
      "-Vaguada",
    ],
  },
  {
    id: 6,
    name: "Finca La Alegría",
    image: "/maps/finca_la_alegria.webp",
    position: { lat: 20.85272, lng: -76.52072 },
    icon: "6",
    simbology: [
      "1-Área de cultivos varios",
      "2-Área de Siembra de Limón",
      "-Arroyo",
    ],
  },
  {
    id: 7,
    name: "Finca La Margarita",
    image: "/maps/finca_la_margarita.webp",
    position: { lat: 20.90083, lng: -76.53986 },
    icon: "7",
    simbology: ["1-Cultivos Varios", "2-Área de Siembra de Limón", "-Arroyo"],
  },
];
